### ISSUE TITLE
How to use dashDB with Cloud Trader?

### ISSUE THREAD

**Issue by rmey** [IBM-Bluemix/JavaCloudTrader#1]
Hello since there is no free SQL Service on Bluemix anymore, I would like to know, if you could make this sample run on dashDB. The connection to dashDB runs fine, with the existing code, but I could not create all tables. Can you please update your example? In dashDB the default table organization is by columns you need to append organize by rows to the the create table statements otherwise the create index statements will fail:
CREATE TABLE holdingejb (PURCHASEPRICE DECIMAL(14, 2), HOLDINGID INTEGER NOT NULL, QUANTITY DOUBLE NOT NULL, PURCHASEDATE TIMESTAMP, ACCOUNT_ACCOUNTID INTEGER, QUOTE_SYMBOL VARCHAR(250)) ORGANIZE BY ROW;
ALTER TABLE holdingejb ADD CONSTRAINT PK_holdingejb PRIMARY KEY (HOLDINGID);
CREATE INDEX HOLDING_ACCOUNTID ON holdingejb(ACCOUNT_ACCOUNTID);

**Comment by rvennam** [comment]
@rmey, if you fixed this, can you create a Pull Request?

**Comment by rvennam** [comment]
[Fixed](https://github.com/IBM-Bluemix/CloudTrader/commit/9113b35ad24f44de202d04b5a81a34193fa941b9) Thanks!
